//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SklepMuzycznyEntities : DbContext
    {
        public SklepMuzycznyEntities()
            : base("name=SklepMuzycznyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresy> Adresy { get; set; }
        public virtual DbSet<Dostawcy> Dostawcy { get; set; }
        public virtual DbSet<ElementyKoszyka> ElementyKoszyka { get; set; }
        public virtual DbSet<Faktury> Faktury { get; set; }
        public virtual DbSet<Kategorie> Kategorie { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<KoszykiZakupowe> KoszykiZakupowe { get; set; }
        public virtual DbSet<Platnosci> Platnosci { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<ProduktyDostawcy> ProduktyDostawcy { get; set; }
        public virtual DbSet<Promocje> Promocje { get; set; }
        public virtual DbSet<Recenzje> Recenzje { get; set; }
        public virtual DbSet<StanMagazynowy> StanMagazynowy { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SzczegolyZamowienia> SzczegolyZamowienia { get; set; }
        public virtual DbSet<Zamowienia> Zamowienia { get; set; }
    }
}
