//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduktyDostawcy
    {
        public int ProduktDostawcaID { get; set; }
        public Nullable<int> ProduktID { get; set; }
        public Nullable<int> DostawcaID { get; set; }
    
        public virtual Dostawcy Dostawcy { get; set; }
        public virtual Produkty Produkty { get; set; }
    }
}
