//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzje
    {
        public int RecenzjaID { get; set; }
        public Nullable<int> ProduktID { get; set; }
        public Nullable<int> KlientID { get; set; }
        public Nullable<int> Ocena { get; set; }
        public string Komentarz { get; set; }
        public Nullable<System.DateTime> DataRecenzji { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Produkty Produkty { get; set; }
    }
}
